### ISSUE TITLE
Cannot ping a redis cluster

### ISSUE THREAD

**Issue by bsergean** [tzickel/jr#2]
I have this example code which works great for talking to a 'normal' redis instance.

```
from justredis import Multiplexer, utf8_bytes_as_strings
import asyncio


async def main():
    redis = Multiplexer({'endpoints': ('localhost', 6379)})
    db = redis.database(decoder=utf8_bytes_as_strings)
    cr = db.commandreply 

    print('Sending PING, receiving %s' % await cr(b'PING'))

    await redis.aclose()


if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

```
$ python example3.py
Sending PING, receiving PONG
```

However if I change the port to the one of a redis cluster, I get this error:

```
$ python example3.py
Traceback (most recent call last):
  File "example3.py", line 27, in <module>
    loop.run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "example3.py", line 16, in main
    await c(b'SET', 'Hello', 'World!')
  File "/Users/bsergeant/src/foss/justredis/justredis/justredis.py", line 782, in command
    await self._multiplexer._send_command(cmd)
  File "/Users/bsergeant/src/foss/justredis/justredis/justredis.py", line 678, in _send_command
    hashslot = await self._get_command_from_cache(cmd)
  File "/Users/bsergeant/src/foss/justredis/justredis/justredis.py", line 750, in _get_command_from_cache
    await (await self._get_connection()).send(info_cmd)
  File "/Users/bsergeant/src/foss/justredis/justredis/justredis.py", line 384, in send
    raise RedisError('Connection already closed')
justredis.justredis.RedisError: Connection already closed
```

I'm running the cluster on port 11000 ; I use [rcc](https://github.com/machinezone/rcc/) as this: `rcc make-cluster` which will create temp config files and initialize the cluster.

**Comment by bsergean** [comment]
Tried to change the code to this, but it still fails.

```
async def main():
    async with Multiplexer({'endpoints': ('localhost', 11000)}) as redis:
        db = redis.database(decoder=utf8_bytes_as_strings)
        cr = db.commandreply 

        print('Sending PING, receiving %s' % await cr(b'PING'))
```

**Comment by tzickel** [comment]
A. are you sure you running the correct code ? because the stack trace shows the exception is in a code which does not exist in your example:
```python
  File "example3.py", line 16, in main
    await c(b'SET', 'Hello', 'World!')
```
B. also, I tried running it in my test suite and it works ok (tests/test_issue.py)
```python
import asyncio

from justredis import Multiplexer, utf8_bytes_as_strings
from .redis_server import RedisServer, start_cluster


async def main():
    servers = start_cluster(6)
    redis = Multiplexer({'endpoints': ('localhost', servers[1].port)})
    db = redis.database(decoder=utf8_bytes_as_strings)
    cr = db.commandreply 

    print('Sending PING, receiving %s' % await cr(b'PING'))

    print('Sending PING, receiving %s' % await redis.run_commandreply_on_all_masters(b'PING'))

    await redis.aclose()
    del cr, db, redis, servers

if __name__ == '__main__':
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```
```bash
justredis$ python -m tests.test_issue
Sending PING, receiving PONG
Sending PING, receiving {('127.0.0.1', 13699): b'PONG', ('127.0.0.1', 12675): b'PONG', ('127.0.0.1', 10151): b'PONG', ('127.0.0.1', 4980): b'PONG', ('127.0.0.1', 19897): b'PONG', ('127.0.0.1', 37577): b'PONG'}

```

**Comment by bsergean** [comment]
C / I'm pretty sure the cluster is ready, I can use it with redis-cli.

$ python -m tests.test_issue
/Users/bsergeant/src/foss/justredis/venv/bin/python: No module named tests.test_issue

Can you show how you are setting up your environment, with the way I do it I cannot import / run your code.

From the top level, I create a virtualenv, activate it, then I type
python setup.py install (or develop)

**Comment by tzickel** [comment]
I meant copy the code from B to a file in the tests directory called test_issue.py (if you cloned this repo with it's test code and did pip install -e . inside the main dir after cloning).

**Comment by bsergean** [comment]
Here is the output for me, I'm running on a mac with python 3.8.1.

With your command I can run your unittest finally, but one test is failing.

```
(venv) justredis$ python3 setup.py test    
running test
running egg_info
writing justredis.egg-info/PKG-INFO
writing dependency_links to justredis.egg-info/dependency_links.txt
writing requirements to justredis.egg-info/requires.txt
writing top-level names to justredis.egg-info/top_level.txt
reading manifest file 'justredis.egg-info/SOURCES.txt'
writing manifest file 'justredis.egg-info/SOURCES.txt'
running build_ext
test_basic (tests.test.TestCluster) ... ERROR
test_misc (tests.test.TestCluster) ... ok
test_moved (tests.test.TestCluster) ... ok
test_outoforder (tests.test.TestCluster) ... ok
test_server (tests.test.TestCluster) ... ok
test_basic_pubsub (tests.test.TestPubSub) ... ok
test_chunk_encoded_command (tests.test.TestServerWithPassword) ... ok
test_eval (tests.test.TestServerWithPassword) ... ok
test_multi (tests.test.TestServerWithPassword) ... ok
test_multidiscard (tests.test.TestServerWithPassword) ... ok
test_multierror (tests.test.TestServerWithPassword) ... ok
test_notallowed (tests.test.TestServerWithPassword) ... ok
test_simple (tests.test.TestServerWithPassword) ... ok
test_some_encodings (tests.test.TestServerWithPassword) ... ok
test_wrongpassword (tests.test.TestServerWithPassword) ... ok

======================================================================
ERROR: test_basic (tests.test.TestCluster)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/bsergeant/src/foss/justredis/tests/test.py", line 11, in asyncwrapper
    return asyncio.get_event_loop().run_until_complete(asyncfunc(*args, **kwargs))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/Users/bsergeant/src/foss/justredis/tests/test.py", line 154, in setUp
    raise Exception('Cluster is down, could not run test')
Exception: Cluster is down, could not run test

----------------------------------------------------------------------
Ran 15 tests in 15.940s

FAILED (errors=1)
Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=15 errors=1 failures=0>
Task was destroyed but it is pending!
task: <Task pending name='Task-2' coro=<Connection._loop() running at /Users/bsergeant/src/foss/justredis/justredis/justredis.py:304> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10ba43730>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-3' coro=<Connection._loop() running at /Users/bsergeant/src/foss/justredis/justredis/justredis.py:304> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10ba43700>()]>>
Task was destroyed but it is pending!
task: <Task pending name='Task-4' coro=<Connection._loop() running at /Users/bsergeant/src/foss/justredis/justredis/justredis.py:304> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x10ba43580>()]>>
```

I don't use docker to run my cluster, I run the command locally, as I don't know how to configure nat etc... so that the guest can see the host ips.

**Comment by tzickel** [comment]
Hmm, since my mac was fried a few weeks ago I don't have a mac to test on, so I've just added to the project Github Actions, a test on mac with homebrew python and redis, and it seems to pass all the tests just fine:
https://github.com/tzickel/justredis/runs/477531948?check_suite_focus=true
Check out the stage "Checking via homebrew", here is the test file (check the mac part):
https://github.com/tzickel/justredis/actions/runs/47540124/workflow

**Comment by bsergean** [comment]
Very cool. Well not sure what was up on my machine when I ran this test.

I have made a ticket on GitHub action machines for them to add a recent redis server btw fyi.

**Comment by bsergean** [comment]
I've started trying to use justredis in cobra (see this branch) https://github.com/machinezone/cobra/blob/feature/redis-cluster/cobras/server/redis_client.py

I am now getting that error again, when trying to run against redis-cluster.

Installing the deps:

```
git clone https://github.com/machinezone/cobra.git
cd cobra
git branch feature/redis-cluster
python3 -mvenv venv
source venv/bin/activate
make dev # (to download deps)
```

To repro the problem:

```
cobra run --redis_library justredis -r redis://localhost:11000
Checking redis://localhost:11000 ..........^C
```

In waitForAllConnectionsToBeReady, in cobras/server/app.py, await redis.ping() fail and I'm getting an exception.

```
                try:
                    redis = RedisClient(
                        url,
                        self.app['redis_password'],
                        self.app['redis_cluster'],
                        self.app['redis_library'],
                    )
                    await redis.connect()
                    await redis.ping()
```

Here's a pdb session:

```
> /Users/bsergeant/src/foss/cobra/cobras/server/redis_client.py(69)ping()
-> return await cr(b'PING')
(Pdb) s
--Call--
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(906)commandreply()
-> async def commandreply(self, *args, **kwargs):
(Pdb) l
901  	    async def command(self, *args, **kwargs):
902  	        cmd = parse_command(self, *args, **kwargs)
903  	        await self._multiplexer._send_command(cmd)
904  	        return cmd
905  	
906  ->	    async def commandreply(self, *args, **kwargs):
907  	        return await (await self.command(*args, **kwargs))()
908  	
909  	    def multi(self, retries=None):
910  	        return MultiCommand(
911  	            self, retries if retries is not None else self._retries, server=self._server
(Pdb) n
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(907)commandreply()
-> return await (await self.command(*args, **kwargs))()
(Pdb) s
--Call--
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(901)command()
-> async def command(self, *args, **kwargs):
(Pdb) l
896  	        self._retries = retries
897  	        self._server = server
898  	        self._scripts = multiplexer._scripts
899  	        self._scripts_sha = multiplexer._scripts_sha
900  	
901  ->	    async def command(self, *args, **kwargs):
902  	        cmd = parse_command(self, *args, **kwargs)
903  	        await self._multiplexer._send_command(cmd)
904  	        return cmd
905  	
906  	    async def commandreply(self, *args, **kwargs):
(Pdb) n
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(902)command()
-> cmd = parse_command(self, *args, **kwargs)
(Pdb) n
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(903)command()
-> await self._multiplexer._send_command(cmd)
(Pdb) s
--Call--
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(781)_send_command()
-> async def _send_command(self, cmd):
(Pdb) n
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(782)_send_command()
-> server = cmd._server
(Pdb) l
777  	                        raise exp
778  	            return self._last_connection
779  	
780  	    # TODO check if closed and dont allow? (or restart)
781  	    async def _send_command(self, cmd):
782  ->	        server = cmd._server
783  	        if not server:
784  	            if isinstance(cmd, MultiCommand) and self._clustered is not False:
785  	                for acmd in cmd._cmds[1:-1]:
786  	                    hashslot = await self._get_command_from_cache(acmd)
787  	                    if hashslot is not None:
(Pdb) n
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(783)_send_command()
-> if not server:
(Pdb) n
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(784)_send_command()
-> if isinstance(cmd, MultiCommand) and self._clustered is not False:
(Pdb) n
> /Users/bsergeant/src/foss/cobra/cobras/server/justredis/justredis.py(790)_send_command()
-> hashslot = await self._get_command_from_cache(cmd)
(Pdb) n
cobras.server.justredis.justredis.RedisError: Connection already closed
```

**Comment by bsergean** [comment]
You already know that, but for completeness, `rcc make-cluster` runs a cluster at port 11000. I can redis-cli -c -p 11000 into it and run simple commands like set foo bar fine.
